import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

export default function Home({data}) {
  return (
    <div className="home_body">
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map(event=>(
        <Link key={event.id} href={`/events/${event.id}`} className="card">
          <div className="image">
            <Image width={600} height={400} alt={event.title} src={event.image} />
          </div>
          <div className="content">
            <h2> {event.title} </h2>
            <p> {event.description} </p>
          </div>
      </Link>
      ))}
      </div>
  )
}

export async function getServerSideProps(){
  const data = await import('@/data.json');
  
  return {
    props:{
      data:data.events_categories
    }
  }
}